### ISSUE TITLE
Missing compile step in instructions

### ISSUE THREAD

**Issue by korva** [Adyen/AdyenCSE-Android#2]
Following the readme instructions was not enough to have adyen-cse included to my project, I had to add

```
dependencies {
  compile(name:'adyencse-1.0.0', ext:'aar') 
}

```

...to get the aar compiled.

Furthermore, I'd suggest looking at hosting the .aar at e.g. jCenter or Maven Central, so you'd have to only add single dependencies line like:

```
dependencies {
    compile 'com.adyen.adyencse:adyencse:1.0.0'
}
```

...instead of the custom download task etc.

**Comment by korva** [comment]
Created PR https://github.com/Adyen/adyen-cse-android/pull/1 with fix suggestion.

**Comment by ericntd** [comment]
Wow, this is shocking
Thanks @korva

**Comment by timon-langlotz** [comment]
Closing this issue since the Adyen CSE library has been made available a while ago. Use `compile "com.adyen.cse:adyen-cse:1.0.5"`.
