### ISSUE TITLE
Why is minSdkVersion set to 19?

### ISSUE THREAD

**Issue by guilhermearaujo** [Adyen/AdyenCSE-Android#6]
Looks like this library uses nothing but `java` and `javax`packages. There are no import from the Android SDK whatsoever. So why is the min SDK version set to 19?

I've copied the classes and successfully encoded a card on Android 15. Is it safe to use on older SDKs?

**Comment by viniciusmo** [comment]
+1

**Comment by guilhermearaujo** [comment]
PR #7 should help. I set it to 15 (Android 4+).

**Comment by timon-langlotz** [comment]
The minimum SDK version has been changed to 9 a while ago. Closing this issue.
