### ISSUE TITLE
Cannot verify CVV without using deprecated methods

### ISSUE THREAD

**Issue by saxophone** [Adyen/AdyenCSE-Android#9]
In this commit f0a19c4efd9a6d391c5e16777cafde12bd76243c, `CardBuilder` was introduced and all the `setX` methods on `Card` were deprecated without explanation. `CardBuilder.build()` requires the card number, cardholder name, and some other fields to be set or else an error is thrown. This is fine for users who are adding a new credit card, but the builder doesn't allow for tokenizing information to verify a CVV.

Tokenizing a card's CVV is explicitly called out as a feature in the Javascript SDK (https://github.com/Adyen/adyen-cse-web#cvc-encryption) and there are no technical limitations on doing so in the iOS CSE SDK. It's still possible to do this in the Android SDK, but doing so requires using the deprecated methods.

For now, I'll use these deprecated methods to verify a CVV, but I think it would be good to explicitly support this common action. Any advice or context around this decision would be greatly appreciated.

**Comment by timon-langlotz** [comment]
Hi @saxophone,

With the last update, we tried to improve the generation process of cards and to add some validation. Unfortunately, we overlooked the features you mentioned that are available on web and iOS. I will look into adding support for these common actions.

For now, you can use the deprecated methods. They were only deprecated to guide new users to use the Builder class, but we are not planning to completely remove them at any time. I'm sorry for any confusion this has caused.

Regards,
Timon

**Comment by timon-langlotz** [comment]
Hi @saxophone,

we have just released version 1.0.5 of the CSE library. This version makes all fields (except for the generation time) optional. Hope this solves all issues you encountered!

Cheers,
Timon
